name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Switch branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -B gh-pages
      - name: Build website
        run: make
      - name: Push changes
        run: |
          git add docs
          git commit -m "update" && git push --set-upstream origin gh-pages || echo "No changes"
